### ISSUE TITLE
Consider hiding the border around expressions once something is typed in them

### ISSUE THREAD

**Issue by jaltekruse** [jaltekruse/Free-Math#207]
The extra boxes around each line adds a lot of visual clutter.

![image](https://user-images.githubusercontent.com/365366/162998604-64ff0cd2-53c3-42b4-abc7-380e90865766.png)
![image](https://user-images.githubusercontent.com/365366/162998644-b69bf4a3-82ea-424b-9fbd-2f731aa12b8f.png)

**Comment by jaltekruse** [comment]
Its very east to remove them unconditionally, probably need to customize mathquill itself to detect an empty box and conditionally set the border.

**Comment by jaltekruse** [comment]
Could also consider hiding the ... menu and the "x" button until the step is selected or has the mouse over it.

**Comment by mscotch1** [comment]
I think this feature has been implemented

**Comment by jaltekruse** [comment]
It has!
